# -*- coding: utf-8 -*-
"""Untitled4.ipynb adlı not defterinin kopyası adlı not defterinin kopyası

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AVNJTBwxoPlczV0m0FhiqBg_uj925E--
"""

class Library:
    def __init__(self):
        self.file = open("books.txt", "a+")

    def __del__(self):
        self.file.close()

    def list_books(self):
        self.file.seek(0)
        books_list = self.file.read().splitlines()
        for book in books_list:
            book_info = book.split(',')
            print("Book Title:", book_info[0])
            print("Book Author:", book_info[1])
            print()

    def add_book(self):
        title = input("Please, enter book title: ")
        author = input("Please, enter author: ")
        first_release_date = input("Please, enter first release date: ")
        number_pages = input("Please, enter number of pages: ")
        book_info = f"{title},{author},{first_release_date},{number_pages}\n"
        self.file.write(book_info)
        print("Adding book was succesful.")

    def remove_book(self):
        title = input("Please, enter the title of the book to remove: ")
        self.file.seek(0)
        books = self.file.readlines()
        self.file.seek(0)
        self.file.truncate()
        for book in books_list:
            if title not in book:
                self.file.write(book)
        print("Removing book was succesful.")


lib = Library()

print("*** MENU ***")
print("a) List Books")
print("b) Add Book")
print("c) Remove Book")

choice = input("Please, enter choice: ")

if choice == 'a':
    lib.list_books()
elif choice == 'b':
    lib.add_book()
elif choice == 'c':
    lib.remove_book()
else:
    print("Choice is not defined.")



