# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_iDtuZ83NQtUhHPBwS-9YdeDqT4bezwh
"""

class Library:
    def __init__(self):
        try:
            self.file = open("books.txt", "a+")
            self.file.seek(0)
            self.books = [line.strip().split(',') for line in self.file.readlines()]
        except IOError:
            print("Error: Unable to access books.txt")
            self.books = []

    def __del__(self):
        self.file.close()

    def list_books(self):
        if not self.books:
            print("Book not exist.")
        else:
            for book in self.books:
                print("title:, (book[0]), author: (book[1])")
                print()

    def add_book(self):
        title = input("Please, enter book title: ")
        author = input("Please, enter book author: ")
        release_date = input("Please, enter release date: ")
        num_pages = input("Please, enter number of pages: ")
        book_info = f"{title},{author},{release_date},{num_pages}\n"
        self.file.write(book_info)
        self.books.append([title, author, release_date, num_pages])
        print("Adding book  successful.")

    def remove_book(self):
        title = input("Please, enter the title of the book to remove: ")
        new_books = [book for book in self.books if book[0] != title]
        if len(new_books) == len(self.books):
            print("Book not found.")
        else:
            self.books = new_books
            self.file.seek(0)
            self.file.truncate()
            for book in self.books:
                book_info = ','.join(book) + '\n'
                self.file.write(book_info)
            print("Removing book  successful.")

lib = Library()

print("--- MENU ---")
print("a) List Books")
print("b) Add Book")
print("c) Remove Book")

while True:
    choice = input("Please, enter your choice (or 'q' to quit): ")

    if choice == 'a':
        lib.list_books()
    elif choice == 'b':
        lib.add_book()
    elif choice == 'c':
        lib.remove_book()
    elif choice.lower() == 'q':
        break
    else:
        print("Choice not defined.")